name: tarbiyapp
description: "TarbiyApp - Educazione islamica dei figli"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  # Obbligatorio per intl e lingue
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  image_picker: ^1.0.0
  cached_network_image: ^3.3.0
  intl: ^0.19.0
  provider: ^6.1.0
  url_launcher: ^6.3.0          # Per Instagram e Segnala problema
  shared_preferences: ^2.3.0    # Per salvare dark mode, lingua, ecc.
  path_provider: ^2.1.0         # Per file locali se serve
  hijri: ^0.5.0                 # Per date islamiche (Ramadan)
  in_app_purchase: ^3.2.0       # Per i piani Premium

flutter:
  uses-material-design: true
  generate: true  # Obbligatorio per flutter_localizations

  assets:
    - assets/avatars/